# Bakes a binary file into a C++ header as a constexpr byte array
#
# Run in script mode:
#   cmake -DINPUT=<binary> -DOUTPUT=<header> -DSYMBOL=<identifier> -P EmbedBinary.cmake

foreach (arg IN ITEMS INPUT OUTPUT SYMBOL)
    if (NOT DEFINED ${arg})
        message(FATAL_ERROR "EmbedBinary.cmake: -D${arg}=... is required")
    endif()
endforeach()

file(READ "${INPUT}" hex HEX)
string(LENGTH "${hex}" hex_length)

set(body "")
set(cursor 0)
while (cursor LESS hex_length)
    string(SUBSTRING "${hex}" ${cursor} 2 byte)
    string(APPEND body "0x${byte},")

    math(EXPR cursor "${cursor} + 2")
    math(EXPR column "(${cursor} / 2) % 16")
    if (column EQUAL 0)
        string(APPEND body "\n    ")
    else()
        string(APPEND body " ")
    endif()
endwhile()

math(EXPR byte_count "${hex_length} / 2")

file(WRITE "${OUTPUT}"
"// Generated by cmake/EmbedBinary.cmake from ${INPUT}. Do not edit.
#pragma once
#include <array>
#include <cstdint>

inline constexpr std::array<uint8_t, ${byte_count}> ${SYMBOL}{
    ${body}
};
")
